[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm run build"]

[phases.start]
cmds = ["cd server && npm start"]

